Implements "corepack elect"
nodejs/corepack pull request #26
Opened 2020-11-23 16:21 UTC by arcanis

See #25 and the documentation added to `README.md` for more details.

In short, this PR implements a proper way for projects such as create-react-app to detect which package manager to use when initializing a project, by gently asking the user only once for all installs that will occur on the machine.

2022-01-19 21:36 UTC, BertsLifee approved these changes

2022-01-19 22:27 UTC, merceyz requested changes
I'm -1 on this, I would prefer if packages check `process.env.npm_config_user_agent` to see which package manager was used and then do whatever they need to based on that.

2022-02-07 12:43 UTC, BertsLifee approved these changes

2023-05-19 20:46 UTC, styfle commented
I agree with merceyz.

For example, `create-next-app` [documents these options](https://nextjs.org/docs/pages/api-reference/create-next-app) for installation:

```sh
npx create-next-app@latest
yarn create next-app
pnpm create next-app
```

And then it uses [`process.env.npm_config_user_agent`](https://github.com/vercel/next.js/blob/d6a3e7d07b6e9f2622463bfbf3a49555173fd5cb/packages/create-next-app/helpers/get-pkg-manager.ts#L4) to determine which package manager was used.

2023-05-20 05:44 UTC, arcanis commented
Yeah, it's an old experiment, from prior those options were implemented. I don't plan to land it anymore.

2023-05-20 05:44 UTC, closed without merging