[WIP] Add support for bun
nodejs/corepack pull request #307
Opened 2023-09-11 18:22 UTC by Ethan-Arrowood

Work in progress - adding support for Bun. I filled out the json as best I see fit.

Investigating tests next

Closes #295

2023-09-11 18:41 UTC, Ethan-Arrowood commented
I don't know why CI is failling at basic install step. Works fine locally for me

2023-09-11 19:06 UTC, uncenter commented
> I don't know why CI is failling at basic install step. Works fine locally for me

Looks like those tests are trying to install yarn?

<img width="1046" alt="image" src="https://github.com/nodejs/corepack/assets/47499684/28e5f884-40ac-4963-84ee-c26e19c0e32a">

2023-09-11 19:33 UTC, merceyz commented
Node.js v20.6 [changed the ESM loader a bit](https://github.com/nodejs/node/pull/47999) so the version of Yarn used by Corepack needs to be updated to a version containing https://github.com/yarnpkg/berry/pull/5677.

Should be a separate PR but you can test with:
```sh
yarn set version canary
yarn
```

2023-09-14 04:30 UTC, Jarred-Sumner commented
Would this be a symlink that does not execute JS in node? I think we should have a hard requirement that if Bun is to be included in Corepack, it must not incur the startup cost penalty of Node before executing `bun` (outside of the initial run to lazily install it)

2023-09-14 05:28 UTC, arcanis commented
All calls to all commands have to go through Corepack, since it has to read the packageManager field to know the version of the package manager to use. It doesn't "cache" this information.

2023-10-06 11:42 UTC, aduh95 commented
@Ethan-Arrowood is it something you're still working on? Is this block on something?

2023-10-06 15:37 UTC, Ethan-Arrowood commented
Hey, no I'm not actively working on this anymore. It looks like we won't get sign off from Bun unless core pack is modified (https://github.com/nodejs/corepack/pull/307#issuecomment-1718747222). I'm happy to help move this along if there is a clear path forward though.

2023-10-06 16:08 UTC, aduh95 commented
FWIW Corepack focuses on improving DX rather than performance, so IMO it wouldn't make sense to have a hard requirement as suggested in https://github.com/nodejs/corepack/pull/307#issuecomment-1718747222. Furthermore I don't think we need Bun permission (although if they feel strongly that we should not do that, it would be rude to not listen, but IIUC it's not what https://github.com/nodejs/corepack/pull/307#issuecomment-1718747222 is saying, please correct me if I'm wrong), so if the community wants Bun in Corepack, that's all that's needed (and passing CI of course). Contributions to improve Corepack performance are of course welcome, but it's not blocking as far as Corepack is concerned.

The path forward is to mark the PR as ready for reviews, and since the tests are already passing, get at least one approval and no objections.

2023-10-06 18:53 UTC, Ethan-Arrowood commented
Okay, I'll mark as ready for review now. And let folks review/approve/reject as they see fit.

2023-10-06 18:53 UTC, Ethan-Arrowood commented
I think this pr may need some tests of its own so if any core pack maintainers could help me with that. It would be appreciated

2023-10-06 21:05 UTC, merceyz requested changes
This needs tests to ensure it works.

2023-11-25 16:15 UTC, altechzilla commented
Hey friends, any update on corepack support for bun? Really looking forward to this. Thanks!

2024-01-31 09:54 UTC, aduh95 commented
> @merceyz can you help me with the tests? I don't understand what to add where

@Ethan-Arrowood you can use https://github.com/nodejs/corepack/pull/333 for inspiration, I think we just need tests that validates the download succeeds and bun is able to run.

2024-02-05 20:53 UTC, Ethan-Arrowood commented
Sorry for the delay. I've added more tests to match that other PR.

2024-02-12 22:54 UTC, aduh95 commented
Bun package on the npm registry is relying on optional dependencies (https://www.npmjs.com/package/bun?activeTab=code). Because Corepack is not a package manager, it has no support for dependencies, so it doesn't work. Worth noting the `bun` binary tries to spawn a subprocess that expects `npm` to be on the $PATH, which seems problematic in the context of Corepack – I would consider it a bug if Corepack needed `npm` to be installed on the PATH to operate.

Support for Bun is still possible to implement into Corepack, but probably not from the npm package.

Note you also need to update the following list: https://github.com/nodejs/corepack/blob/12f1c31a0decb867f91f31ffb0cadf34ce9f0673/sources/types.ts#L4-L8

2024-02-16 20:48 UTC, Ethan-Arrowood commented
I'm not sure I understand, so we need to find a different url for installing bun? Would their install script suffice `https://bun.sh/install` ? 

I'm also going to re-emphasize that I really don't need to be driving this anymore. If this is more complex, I'd rather the Bun folks finish the swing here.

2025-01-07 16:11 UTC, MinskLeo commented
Hi guys! What's the latest status of adding bun support? Feels like it's kinda hard to add and it's blocked with smth? What needs to be done in order to add bun support into Corepack at this moment?

2025-01-08 16:22 UTC, closed without merging