fix: do not hard fail if Corepack home folder cannot be created
nodejs/corepack pull request #382
Opened 2024-02-20 12:44 UTC by aduh95

Fixes: https://github.com/nodejs/corepack/issues/379

2024-02-20 13:11 UTC, merceyz requested changes
Could you add a test?

One that runs `HOME="/tmp/some/folder/here" yarn -v` should be enough to reproduce the issue.

2024-02-20 13:31 UTC, aduh95 commented
The reason the tests didn't catch it is because we specifically disable it: https://github.com/nodejs/corepack/blob/4a8ce6d42f081047a341f36067696346c9f3e1ea/tests/main.test.ts#L14

If we re-enable it, it will cause the nock to be outdated as soon as Yarn publish a new version (if we use `yarn -v`) which is not ideal.

2024-02-20 15:17 UTC, merceyz approved these changes

2024-02-21 03:11 UTC, anonrig approved these changes

2024-02-21 03:15 UTC, merged