Marks `yarn init` as a transparent command
nodejs/corepack pull request #410
Opened 2024-02-27 10:59 UTC by arcanis

New projects should use the newest versions when setup. Adding `yarn init` as a transparent command means that people running it will automatically have the `packageManager` field set to `4.0.1+...`.

Projects that don't list package managers will still execute Yarn 1.x, and so will other Yarn commands executed from outside any package directory (`yarn config set`, etc).

2024-02-27 11:43 UTC, merceyz requested changes
We need to solve https://github.com/nodejs/corepack/issues/202#issuecomment-1295811185 first.

2024-02-27 12:14 UTC, aduh95 approved these changes
That seems a good change regardless of fixing the other bug.

2024-03-01 11:43 UTC, arcanis commented
I agree with @aduh95 - the two problems are separate, I don't think this PR should be blocked until I send a fix for the other one.

2024-03-03 12:51 UTC, arcanis commented
Going to work on the "transparent version should be ignored if the local version supports the command" issue in a separate PR. Merging this one in the meantime.

2024-03-03 12:51 UTC, merged