chore: use renameSafe where applicable
nodejs/corepack pull request #515
Opened 2024-07-11 19:54 UTC by wojtekmaj

Code I removed is literally renameSafe's body, so I replaced it with renameSafe.

2024-07-11 20:15 UTC, merceyz requested changes

2024-07-11 20:15 UTC, merceyz commented on sources/corepackUtils.ts
> +    renameSafe(tmpFolder, installFolder);
```suggestion
    await renameSafe(tmpFolder, installFolder);
```

2024-07-11 21:09 UTC, merceyz approved these changes

2024-07-12 08:48 UTC, aduh95 approved these changes

2024-07-12 08:48 UTC, merged